name: Build and deploy JAR app to Azure Web App - SIWBooks

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7181CD29E9A741748F87567C79B308AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B879717D72D04ABCBA32414FEA7C751C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EC294265129E4060B74211699A9BEF96 }}

      - name: Set environment variables in Azure App Service
        run: |
          az webapp config appsettings set --name SIWBooks \
            --resource-group SIW \
            --settings \
              DB_HOST=${{ secrets.DB_HOST }} \
              DB_USERNAME=${{ secrets.DB_USERNAME }} \
              DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }} \
              GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SIWBooks'
          slot-name: 'Production'
          package: '*.jar'
